# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-27 11:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('empsno', models.IntegerField(blank=True, db_column='EmpSno', null=True)),
                ('arrivaltime', models.DateTimeField(blank=True, db_column='ArrivalTime', null=True)),
                ('departuretime', models.DateTimeField(blank=True, db_column='DepartureTime', null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('inserteddate', models.DateTimeField(blank=True, db_column='InsertedDate', null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('loginip', models.CharField(blank=True, db_column='LoginIP', max_length=50, null=True)),
                ('logoutip', models.CharField(blank=True, db_column='LogoutIP', max_length=50, null=True)),
                ('arrivaltime_bio', models.DateTimeField(blank=True, db_column='ArrivalTime_Bio', null=True)),
                ('departuretime_bio', models.DateTimeField(blank=True, db_column='DepartureTime_Bio', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Adjustment_Request',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('Empsno', models.IntegerField(blank=True, db_column='EmpSno', null=True)),
                ('Date', models.DateField(db_column='Date')),
                ('Categories', models.CharField(blank=True, db_column='categories', max_length=100, null=True)),
                ('Reason', models.CharField(blank=True, db_column='Reason', max_length=200, null=True)),
                ('Att_Granted_Hr', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject')], db_column='By_Hr', max_length=50, null=True)),
                ('Att_Granted_M', models.CharField(blank=True, db_column='By_M', max_length=50, null=True)),
                ('M_Description', models.CharField(blank=True, db_column='M_Description', max_length=100, null=True)),
                ('day', models.CharField(blank=True, db_column='day', max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance_Adjustment_Request',
            },
        ),
        migrations.CreateModel(
            name='Attendance_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empsno', models.AutoField(db_column='EmpSno', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(db_column='Fname', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ .-/]*$', 'Only characters are allowed.')])),
                ('Last_Name', models.CharField(blank=True, db_column='Lname', max_length=50, null=True)),
                ('DOB', models.DateField(db_column='DOB')),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_column='Gender', max_length=10)),
                ('Designation', models.CharField(db_column='Role', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ .-/]*$', 'Only characters are allowed.')])),
                ('Residential_Address', models.CharField(db_column='Address', max_length=200)),
                ('Contact', models.CharField(blank=True, db_column='Phone', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only integers are allowed')], verbose_name='Contact Number')),
                ('Mobile', models.CharField(db_column='Mobile', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only integers are allowed'), django.core.validators.MinLengthValidator(10)], verbose_name='Mobile Number')),
                ('User_Name', models.CharField(db_column='Username', max_length=50)),
                ('Password', models.CharField(db_column='PW', max_length=500)),
                ('Date_of_Joining', models.DateField(db_column='JoiningDate')),
                ('Bank_Acc_No', models.CharField(blank=True, db_column='BankAccNo', max_length=50, null=True)),
                ('Leave_Allocated', models.CharField(db_column='LeaveAllocated', max_length=5)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('Emp_Status', models.CharField(blank=True, db_column='EmpStatus', editable=False, max_length=20, null=True)),
                ('Leave_Transferred', models.CharField(blank=True, db_column='LeaveTransferred', editable=False, max_length=10, null=True)),
                ('Status_Bit', models.IntegerField(blank=True, editable=False, null=True)),
                ('Leaving_Ddate', models.DateField(blank=True, db_column='LeavingDate', editable=False, null=True)),
                ('Bio_Employee_Code', models.IntegerField(blank=True, db_column='Bio_EmployeeCode', editable=False, null=True)),
                ('PAN_Number', models.CharField(blank=True, db_column='PanNumber', max_length=50, null=True)),
                ('Qualification', models.CharField(db_column='Qualification', max_length=50)),
                ('User_Type', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], db_column='user_type', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('Id_new', models.AutoField(db_column='Id_new', primary_key=True, serialize=False)),
                ('Holiday_Date', models.DateField(db_column='Hdate')),
                ('Description', models.CharField(db_column='Description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('empsno', models.IntegerField(blank=True, db_column='EmpSno', null=True)),
                ('Applied_Date', models.DateTimeField(auto_now_add=True, db_column='AppliedDate', null=True)),
                ('Applied_Reason', models.CharField(blank=True, db_column='AppliedReason', max_length=1000, null=True)),
                ('leave_Granted_Date', models.DateField(blank=True, db_column='LeaveGrantedDate', null=True)),
                ('leave_Granted_Hr', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject')], db_column='By_Hr', max_length=50, null=True)),
                ('leave_Granted_M', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject')], db_column='By_M', max_length=50, null=True)),
                ('M_Description', models.CharField(blank=True, db_column='M_Description', max_length=100, null=True)),
                ('leave_From', models.DateField(blank=True, db_column='Leavefrom', null=True)),
                ('leave_To', models.DateField(blank=True, null=True)),
                ('Fday', models.CharField(blank=True, db_column='Fday', max_length=10, null=True)),
                ('Tday', models.CharField(blank=True, db_column='Tday', max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leaves',
                'db_table': 'Leaves',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('empsno', models.AutoField(db_column='EmpSno', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(db_column='Fname', max_length=50)),
                ('Last_Name', models.CharField(blank=True, db_column='Lname', max_length=50, null=True)),
                ('DOB', models.DateField(db_column='DOB')),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_column='Gender', max_length=10)),
                ('Designation', models.CharField(db_column='Role', max_length=50)),
                ('Residential_Address', models.CharField(db_column='Address', max_length=200)),
                ('Contact', models.CharField(db_column='Phone', max_length=20)),
                ('Mobile', models.CharField(db_column='Mobile', max_length=20)),
                ('User_Name', models.CharField(db_column='Username', max_length=50)),
                ('Password', models.CharField(db_column='PW', max_length=500)),
                ('Date_of_Joining', models.DateField(db_column='JoiningDate')),
                ('Bank_Acc_No', models.CharField(blank=True, db_column='BankAccNo', max_length=50, null=True)),
                ('Leave_Allocated', models.CharField(db_column='LeaveAllocated', max_length=5)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('Emp_Status', models.CharField(blank=True, db_column='EmpStatus', editable=False, max_length=20, null=True)),
                ('Leave_Transferred', models.CharField(blank=True, db_column='LeaveTransferred', editable=False, max_length=10, null=True)),
                ('Status_Bit', models.IntegerField(blank=True, editable=False, null=True)),
                ('Leaving_Ddate', models.DateField(blank=True, db_column='LeavingDate', editable=False, null=True)),
                ('Bio_Employeecode', models.IntegerField(blank=True, db_column='Bio_EmployeeCode', editable=False, null=True)),
                ('PAN_Number', models.CharField(blank=True, db_column='PanNumber', max_length=50, null=True)),
                ('Qualification', models.CharField(db_column='Qualification', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='notice_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Notice_All',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Manager'),
        ),
    ]
